-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        5.5.60-MariaDB - mariadb.org binary distribution
-- 服务器操作系统:                      Win32
-- HeidiSQL 版本:                  9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- 导出 myweb 的数据库结构
CREATE DATABASE IF NOT EXISTS `myweb` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `myweb`;

-- 导出  表 myweb.challenge 结构
CREATE TABLE IF NOT EXISTS `challenge` (
  `title` varchar(255) NOT NULL,
  `cid` int(11) NOT NULL AUTO_INCREMENT,
  `flag` varchar(255) NOT NULL,
  `type` int(11) NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  `description` tinytext,
  `solved_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- 正在导出表  myweb.challenge 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `challenge` DISABLE KEYS */;
/*!40000 ALTER TABLE `challenge` ENABLE KEYS */;

-- 导出  表 myweb.tools 结构
CREATE TABLE IF NOT EXISTS `tools` (
  `cid` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `pic_address` varchar(255) NOT NULL DEFAULT '0',
  `name` varchar(50) NOT NULL DEFAULT '0',
  `flag` varchar(255) DEFAULT NULL,
  `description` text,
  `platform` varchar(255) NOT NULL DEFAULT '0',
  `link` varchar(255) DEFAULT NULL,
  `isuse` varchar(50) DEFAULT '0',
  `solved_number` int(11) DEFAULT '0',
  `subtype` varchar(255) NOT NULL DEFAULT '0',
  `myuse` varchar(50) NOT NULL DEFAULT '0',
  `isopen` varchar(50) NOT NULL DEFAULT '0',
  `address` varchar(50) DEFAULT '0',
  PRIMARY KEY (`cid`) USING BTREE,
  UNIQUE KEY `Index 2` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=675 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- 正在导出表  myweb.tools 的数据：~59 rows (大约)
/*!40000 ALTER TABLE `tools` DISABLE KEYS */;
REPLACE INTO `tools` (`cid`, `type`, `title`, `pic_address`, `name`, `flag`, `description`, `platform`, `link`, `isuse`, `solved_number`, `subtype`, `myuse`, `isopen`, `address`) VALUES
	(551, '0', 'SUCURI', 'assets/images/tools/SUCURI.jpg', 'SUCURI', '0', 'Quick tests for malware, blacklist status, injected spam and deface, and help clean and protect web site from online threats.', 'To work on any website platform| including WordPress| Joomla| Magento| Drupal| phpBB| etc', 'https://sitecheck.sucuri.net/?cjevent=79ff96c618bd11ec830801170a1c0e12&cj_aid=13948096&cj_pid=8092889&cj_cid=4761150', NULL, 0, 'Scan websites online for vulnerabilities and malware', '0', 'business', ''),
	(553, '0', 'QUTTERA', 'assets/images/tools/QUTTERA.jpg', 'QUTTERA', '0', 'Check the sites being tested for malware and exploits. Scan sites for malicious files, suspicious files, potentially suspicious files, PhishTank, Secure Browsing (Google, Yandex) and malware domain lists', 'To work on any website platform', 'https://quttera.com', NULL, 0, 'Scan websites online for vulnerabilities and malware', '1', 'business', 'teamviewer://hello3'),
	(554, '0', 'Intrude', 'assets/images/tools/Intrude.jpg', 'Intrude', '0', 'A powerful cloud-based vulnerability scanner designed to find vulnerabilities throughout your Web application infrastructure. It provides government services and a bank-level security scanning engine without complexity. Security checks include determining: Missing patches Configuration errors, Web application issues, such as SQL injection, and cross-site scripting, CMS issues. It can save detection time by prioritizing results based on their context and proactively scanning for the latest vulnerabilities in the system. It also integrates with major cloud providers (AWS, GCP, Azure) as well as Slack.', 'To work on any website platform', 'https://www.intruder.io/?utm_source=google&utm_medium=cpc&utm_campaign=USA%7CSearch%7CBrand&utm_term=intruder&gclid=Cj0KCQjwnJaKBhDgARIsAHmvz6cF0xdx9v1Qd34X9Gm64EujSViN7VSAhl-Qxgy4y9Nfwv4yBl7JYgMaAjVOEALw_wcB', NULL, 0, 'Scan websites online for vulnerabilities and malware', '0', 'Free trial for 30 days', 'teamviewer://hello4'),
	(555, '0', 'UpGuard', 'assets/images/tools/UpGuard.jpg', 'UpGuard', '1', 'External risk assessment tools that use publicly available information to score. Help quickly get the security status of the website, the test results are divided into the following categories: website risk, email risk, network security, phishing and malware, brand protection', 'To work on any website platform', 'https://webscan.upguard.com/', NULL, 0, 'Scan websites online for vulnerabilities and malware', '1', 'business', 'teamviewer://hello5'),
	(556, '0', 'SiteGuarding', 'assets/images/tools/SiteGuarding.jpg', 'SiteGuarding', '0', 'Blacklists, injected spam, smears, etc. The scanner is compatible with WordPress, Joomla, Drupal, Magento, osCommerce, Bulletin and other platforms. It can also remove malware from a website, so they can be very useful if a website is infected with a virus', 'To work on any website platform', 'https://www.siteguarding.com/en', NULL, 0, 'Scan websites online for vulnerabilities and malware', '1', 'business', 'teamviewer://hello6'),
	(557, '0', 'Mozilla', 'assets/images/tools/Mozilla.jpg', 'Mozilla', '0', 'Helps site owners check various security elements. It validates against OWASP header security, TLS best practices, and performs third-party testing from SSL LABS, High-tech Bridges, security headers, HSTS Preload, and more.', 'To work on any website platform', 'https://observatory.mozilla.org', NULL, 0, 'Scan websites online for vulnerabilities and malware', '1', 'business', 'teamviewer://hello7'),
	(558, '0', 'Web Cookies Scanner', 'assets/images/tools/Web Cookies Scanner.jpg', 'Web Cookies Scanner', '1', 'Free all-in-one security tool for scanning Web applications. It can search for vulnerabilities and privacy issues on HTTP cookies, Flash applets, HTML5 localStorage and sessionStorage, Supercookies and Evercookies.The tool also provides free URL malware scanners as well as HTTP, HTML and SSL/TLS vulnerability scanners. To use this tool, simply enter the full domain name of the site and click Check! Later, you will get the full vulnerability report, showing details of all the problems found and the overall privacy impact score.Free access to on-demand services is unlimited, or you can subscribe to a free trial of fully automated RESTful apis with different plans that offer 100 to unlimited API scans per month.', 'To work on any website platform', 'https://www.cookieyes.com/cookie-scanner/', NULL, 0, 'Scan websites online for vulnerabilities and malware', '1', 'business', 'teamviewer://hello8'),
	(559, '0', 'Detectify', 'assets/images/tools/Detectify.jpg', 'Detectify', '0', 'It provides automatic security and asset monitoring capabilities for domain and Web application security services and claims to be able to detect more than 1,500 vulnerabilities. Its vulnerability scanning features include OWASP Top 10, CORS, Amazon S3 buckets and DNS misconfiguration.The asset monitoring service continuously monitors subdomains, searches for malicious takeovers and alerts when exceptions are detected.Detectify offers three pricing plans: Starter, Professional, and Enterprise. All of this starts with a 14-day free trial that doesn\'t require a credit card. .', 'To work on any website platform', 'https://detectify.com', NULL, 0, 'Scan websites online for vulnerabilities and malware', '0', 'Free trial for 14 days', 'teamviewer://hello9'),
	(560, '0', 'Probely', 'assets/images/tools/Probely.jpg', 'Probely', '0', 'Provides virtual security experts that can be added to developers, security teams, DevOps, or SaaS businesses. The security expert scans the Web application for any vulnerabilities. Think of Probely as a family doctor that can provide regular diagnostics and tell you how to fix any problems, and a tool built primarily for developers to give them more independence when doing security testing. Its API-First development approach ensures that all functionality is provided First on the API version of the service. It has a number of pricing plans, including a free one with basic scanning capabilities.', 'To work on any website platform', 'https://probely.com', NULL, 0, 'Scan websites online for vulnerabilities and malware', '0', 'Multiple pricing plans| basic features free', 'teamviewer://hello10'),
	(561, '0', 'Pentest-Tools', 'assets/images/tools/Pentest-Tools.jpg', 'Pentest-Tools', '0', 'Solutions for information collection, Web application testing, CMS testing, infrastructure testing, and SSL testing. Web site scanners can find common Web application vulnerabilities and server configuration problems. There is a Light version of the tool that can perform passive Web security scans. It can detect many vulnerabilities, including insecure cookie Settings, insecure HTTP headers, and outdated server software. However, up to 2 free full scans of the site can be performed for a full evaluation. The results report contains details about vulnerabilities such as local file inclusion, SQL injection, OS command injection, XSS, etc.', 'To work on any website platform', 'https://pentest-tools.com/website-vulnerability-scanning/website-scanner', NULL, 0, 'Scan websites online for vulnerabilities and malware', '0', 'Maximum 2 free full scans', 'teamviewer://hello11'),
	(562, '1', 'Nessus', 'assets/images/tools/Nessus.jpg', 'Nessus', '0', 'Nessus is a remote security scan software that runs on Linux, BSD, Solaris, and other operating systems. It is multi-threaded, plugg-based software with a good GTK interface, capable of performing over 1200 remote security checks, powerful report output capability, capable of generating security reports in HTML, XML, LaTeX and ASCII text formats, and providing suggestions for solving every security problem found.', 'Linux/BSD/Unix', 'http://www.nessus.org/', NULL, 0, 'Risk Assessment', '1', 'Open Source', 'teamviewer://hello12'),
	(563, '1', 'Snort', 'assets/images/tools/Snort.jpg', 'Snort', '0', 'Snort is a lightweight network intrusion detection system that can perform real-time traffic analysis and packet recording on IP networks. It can not only carry out protocol analysis, content retrieval, content matching, but also can be used to detect a large number of attacks or illegal detection such as buffer overflow, hidden port scanning, CGI attacks, SMB detection, operating system fingerprint identification and so on. Snort uses flexible rules to describe what traffic should be collected or ignored, and provides a modular detection engine.', 'Linux/BSD/Unix/Windows', 'https://www.snort.org/downloads', NULL, 0, 'Free intrusion detection system', '1', 'Open Source', 'teamviewer://hello13'),
	(564, '1', 'Netcat', 'assets/images/tools/Netcat.jpg', 'Netcat', '0', 'A simple and useful tool for reading and writing data over a TCP or UDP network connection. It is designed to be a stable backdoor tool that can be easily driven directly by other programs and scripts. It\'s also a powerful network debugging and probing tool that can set up almost any type of network connection you need, and has several interesting built-in features.', 'Linux/BSD/Unix/Windows', 'https://nc110.sourceforge.io', NULL, 0, 'Internet Swiss Army knife', '1', 'Open Source', 'teamviewer://hello14'),
	(565, '1', 'TCPDump/WinDump', 'assets/images/tools/TCPDumpWinDump.jpg', 'TCPDump/WinDump', '0', 'Command line based network packet analysis and sniffing tool. It can match the rules of the packet header to display. You can use this tool to find network problems or to monitor network conditions. WinDump is a port of Tcpdump on Windows.', 'Linux/BSD/Unix/Windows', 'http://www.tcpdump.org', NULL, 0, 'Excellent sniffer for network monitoring and data collection', '1', 'Open Source', 'teamviewer://hello15'),
	(566, '1', 'Hping2', 'assets/images/tools/Hping2.jpg', 'Hping2', '0', 'Hping2 sends customized ICMP/UDP/TCP packets to the destination address and displays the packet response. It has a convenient Traceroute mode and supports IP sharding. This tool is especially useful for traceroute, ping, and probing hosts behind a firewall.', 'Linux/BSD/Unix', 'http://www.hping.org', NULL, 0, 'Ping-like network detection tool', '1', 'Open Source', 'teamviewer://hello16'),
	(567, '1', 'GFI LANguard', 'assets/images/tools/GFI LANguard.jpg', 'GFI LANguard', '0', 'LANguard scan the network and draw such as service pack level of each machine, Missing security patches, open shares, open ports, running services and applications, registry keys, weak passwords, user and group scan information reports. The scan result is output as a report in HTML format, which can be customized. ', 'Windows', 'http://www.gfi.com/lannetscan/', NULL, 0, 'Commercial network security scanning software', '0', '', 'teamviewer://hello17'),
	(568, '1', 'Ettercap', 'assets/images/tools/Ettercap.jpg', 'Ettercap', '0', 'Ettercap is a comprehensive suite for man in the middle attacks. It features sniffing of live connections, content filtering on the fly and many other interesting tricks. It supports active and passive dissection of many protocols and includes many features for network and host analysis.', 'Linux/BSD/Unix/Windows', 'https://www.ettercap-project.org', NULL, 0, 'Understand the current situation in the LAN| and check the security of the network switching environment', '1', 'Open Source', 'teamviewer://hello18'),
	(569, '1', 'John the Ripper', 'assets/images/tools/John the Ripper.jpg', 'John the Ripper', '0', '"John the Ripper is an Open Source password security auditing and password recovery tool available for many operating systems. John the Ripper jumbo supports hundreds of hash and cipher types, including for: user passwords of Unix flavors (Linux, *BSD, Solaris, AIX, QNX, etc.), macOS, Windows, ""web apps"" (e.g., WordPress), groupware (e.g., Notes/Domino), and database servers (SQL, LDAP, etc.); network traffic captures (Windows network authentication, WiFi WPA-PSK, etc.); encrypted private keys (SSH, GnuPG, cryptocurrency wallets, etc.), filesystems and disks (macOS .dmg files and ""sparse bundles"", Windows BitLocker, etc.), archives (ZIP, RAR, 7z), and document files (PDF, Microsoft Office\'s, etc.) These are just some of the examples - there are many more."', 'Linux/BSD/Unix/Windows', 'https://www.openwall.com/john/', NULL, 0, 'Password security audit and password recovery tool and hashed password cracker', '1', 'Open Source', 'teamviewer://hello19'),
	(570, '1', 'OpenSSH/SSH', 'assets/images/tools/OpenSSHSSH.jpg', 'OpenSSH/SSH', '0', 'OpenSSH is the premier connectivity tool for remote login with the SSH protocol. It encrypts all traffic to eliminate eavesdropping, connection hijacking, and other attacks. In addition, OpenSSH provides a large suite of secure tunneling capabilities, several authentication methods, and sophisticated configuration options.', 'Linux/BSD/Unix/Windows', 'http://www.openssh.com', NULL, 0, 'A secure method of accessing a remote computer', '1', 'Open Source/business', 'teamviewer://hello20'),
	(571, '1', 'Tripwire', 'assets/images/tools/Tripwire.jpg', 'Tripwire', '0', 'Tripwire is a file and directory integrity check tool that helps system administrators and users monitor changes to important files and directories. By setting some basic system policies, Tripwire notifies the system administrator when a file is corrupted or tampered with. The commercial version of Tripwire is expensive, there is a free open source Linux version available at Tripwire.Org, and UNIX users may also want to consider AIDE (http://www.cs.tut.fi/~rammer/aide.html), It\'s a free alternative to Tripwire.', 'Linux/BSD/Unix/Windows', 'https://www.tripwire.com', NULL, 0, 'Powerful data integrity check tool', '1', 'business', 'teamviewer://hello21'),
	(572, '1', 'Nikto 2', 'assets/images/tools/Nikto 2.jpg', 'Nikto 2', '0', 'Scanning software that can test various security items on web servers can scan for more than 2,000 potentially dangerous files, CGI and other problems on more than 200 servers. It also uses the LibWhiske library, but is usually updated more frequently than Whisker.', 'Linux/BSD/Unix/Windows', 'https://cirt.net/Nikto2', NULL, 0, 'Comprehensive Web scanner', '1', 'Open Source', 'teamviewer://hello22'),
	(573, '1', 'Kismet', 'assets/images/tools/Kismet.jpg', 'Kismet', '0', '802.11b network sniffing and analysis program, features: Supports most wireless network cards, can automatically implement network IP blocking detection through UDP, ARP, DHCP packets, can list Cisco devices through Cisco Discovery protocol, weakly encrypted packet records, and Ethereal, tcpdump compatible packet dump files, Map the detected network and estimate the network range.', 'Linux/BSD/Unix/Windows', 'https://www.kismetwireless.net', NULL, 0, 'Wireless sniffer', '1', 'Open Source', 'teamviewer://hello23'),
	(574, '1', 'SAINT', 'assets/images/tools/SAINT.jpg', 'SAINT', '0', 'Commercial risk assessment tools running on Unix-like platforms', 'Linux/BSD/Unix', 'https://www.carson-saint.com/products/saint-security-suite/', NULL, 0, 'A comprehensive networking tool for UNIX platform security administrators', '0', 'business', 'teamviewer://hello24'),
	(575, '1', 'N-Stealth', 'assets/images/tools/N-Stealth.jpg', 'N-Stealth', '0', '"N-stealth is a commercial Web server security scanner that is typically upgraded more frequently than free Web scanners such as Whisker and Nikto. N-stealth developers\' claims of ""over 20,000 defect and exploit data"" and ""numerous additional defect checks per day"" are highly suspect. All the common risk assessment tools, such as Nessus, ISS, Retina, SAINT, and SARA, already have Web scanning components, but they may not be as flexible and updated as N-Stealth. N-stealth does not publish the source code."', 'Windows', 'http://www.nstalker.com/products/editions/free/', NULL, 0, 'Web server scanning tool', '0', 'business', 'teamviewer://hello25'),
	(576, '1', 'Honeyd', 'assets/images/tools/Honeyd.jpg', 'Honeyd', '0', 'Honeyd is a little daemon that can create virtual hosts on a network. Virtual hosts can be configured to run any service and have the proper service TCP features so that they look like they\'re running on a particular version of the operating system. Honeyd can equip a host with multiple addresses in a simulated LAN environment, and ping and traceroute virtual hosts. Any type of service on a virtual host can be emulated according to a simple configuration file. Honeyd can also proxy a host instead of emulating it.', 'Linux/BSD/Unix/Windows', 'http://www.citi.umich.edu/u/provos/honeyd/', NULL, 0, 'Create a virtual host on the network', '0', 'Open Source', 'teamviewer://hello26'),
	(577, '1', 'Stunnel', 'assets/images/tools/Stunnel.jpg', 'Stunnel', '0', 'Stunnel is a proxy designed to add TLS encryption functionality to existing clients and servers without any changes in the programs\' code. Its architecture is optimized for security, portability, and scalability (including load-balancing), making it suitable for large deployments.Stunnel uses the OpenSSL library for cryptography, so it supports whatever cryptographic algorithms are compiled into the library. It can benefit from the FIPS 140-2 validation of the OpenSSL FIPS Object Module, as long as the building process meets its Security Policy. A scanned FIPS 140-2 Validation Certificate document is available for download on the NIST web page. The OpenSSL FIPS 140-2 module is currently only available for OpenSSL 1.0.2. FIPS-enabled Windows installers of stunnel are available on request with our customer support plans.', 'Linux/BSD/Unix/Windows', 'http://www.stunnel.org/', NULL, 0, 'SSL encryption shell for multiple purposes', '0', 'Open Source', 'teamviewer://hello27'),
	(578, '5', 'Kali Linux', 'assets/images/tools/Kali Linux.jpg', 'Kali Linux', '0', 'Kali Linux is one of the most common cybersecurity tools. It is an operating system containing at least 300 different tools for security auditing. Kali Linux provides various tools that organizations use to scan their networks and IT systems for vulnerabilities. The main benefit of Kali Linux is that it can be used by users with different levels of cybersecurity knowledge. As such, it does not require an advanced cybersecurity specialist to be competent. Most of the tools available in the operating system are executable, meaning that users can monitor and manage the security of their network systems with a single click. Kali Linux is readily available for use.', '', 'https://www.kali.org', NULL, 0, 'Penetration testing tools', '0', '', 'teamviewer://hello28'),
	(579, '5', 'Metasploit', 'assets/images/tools/Metasploit.jpg', 'Metasploit', '0', 'Metasploit consists of an excellent collection containing different tools for carrying out penetration testing exercises. IT experts and cybersecurity professionals use Metasploit to accomplish varying security objectives. These include identifying vulnerabilities in network or system, formulating strategies for strengthening cybersecurity defense and managing the completed security evaluations. Metasploit can test the security of different systems, including online-based or web-based applications, networks, servers, among others. Metasploit identifies all new security vulnerabilities as they emerge, thus ensuring round-the-clock security. Also, security professionals often use the tool to evaluate IT infrastructure security against vulnerabilities reported earlier.', '', 'https://www.metasploit.com', NULL, 0, '', '0', '', 'teamviewer://hello29'),
	(580, '6', 'Cain and Abel', 'assets/images/tools/Cain and Abel.jpg', 'Cain and Abel', '0', 'Cain and Abel is one of the earliest cybersecurity tools used to uncover vulnerabilities in Windows Operating systems. Cain and Abel enable security professionals to discover weaknesses in the password security of systems running on the Windows operating system. It is a free cybersecurity tool used for password recovery. It has many functionalities, which include the ability to record VoIP communications. Also, Cain and Abel can analyze routing protocols to determine whether routed data packets can be compromised. Additionally, Cain and Abel reveal cached passwords, password boxes and uses brute force attacks to crack encrypted passwords. Moreover, the tool also decodes scrambled passwords and highly effective in cryptoanalysis. Companies should consider using Cain and Abel as a starting point for all packet sniffing processes.', '', 'https://cain_abel.en.downloadastro.com', NULL, 0, 'Password auditing and packet sniffers cybersecurity tools', '0', '', 'teamviewer://hello30'),
	(581, '6', 'Wireshark', 'assets/images/tools/Wireshark.jpg', 'Wireshark', '1', 'Wireshark, formerly known as Ethereal, is a console-based cybersecurity tool. Wireshark is an excellent tool for analyzing network protocols and hence used for analyzing network security in real-time. Wireshark analyzes network protocols and sniffs the network in real-time to assess the presence of vulnerabilities. Wireshark is a useful tool for scrutinizing all details related to network traffic at different levels, ranging from the connection level to all pieces of data packets. Security professionals use Wireshark to capture data packets and investigate the characteristics which individual data packets exhibit. The obtained information permits easy identification of weaknesses in the network��s security.', '', 'https://www.wireshark.org', NULL, 0, '', '0', '', 'teamviewer://hello31'),
	(583, '6', 'Tcpdump', 'assets/images/tools/Tcpdump.jpg', 'Tcpdump', '0', 'Tcpdump is a handy tool for sniffing data packets in a network. Cybersecurity professionals use it to monitor as well as log TCP and IP traffic communicated through a network. Tcpdump is a command-based software utility and analyzes network traffic between the computer it is executed in and the network the traffic passes through. More specifically, Tcpdump tests the security of a network by capturing or filtering TCP/IP data traffic transferred through or received over the network on a particular interface. Depending on the command used, Tcpdump describes the packet contents of network traffic using different formats.', '', 'https://www.tcpdump.org', NULL, 0, '', '0', '', 'teamviewer://hello33'),
	(584, '7', 'Netstumbler', 'assets/images/tools/Netstumbler.jpg', 'Netstumbler', '0', 'Netstumbler is a free cybersecurity tool designed for systems running on Windows operating systems. The tool allows security experts to identify open ports on a network. It is also used for wardriving purposes. Netstumbler was developed for Windows systems only; hence there is no provision of source codes. The tool utilizes a WAP-seeking approach when searching for open ports, causing it to be among the most popular tools for network defense. It also popular because of its ability to identify network vulnerabilities that may not be present in other types of security tools.', 'Windows', 'http://www.netstumbler.com/downloads/', NULL, 0, 'Cybersecurity tools for network defense', '0', 'no provision of source codes', 'teamviewer://hello34'),
	(585, '7', 'Aircrack-ng', 'assets/images/tools/Aircrack-ng.jpg', 'Aircrack-ng', '0', 'Aircrack-ng contains a comprehensive set of utilities used to analyze the weaknesses of Wi-Fi network security. Cybersecurity professionals use it to capture data packets communicated through a network for continuous monitoring. Also, Aircrack-ng provides functionalities for exporting captured data packets to text files to be subjected to more security assessments. Besides, it permits capture and injection, which is essential in assessing the performance of network cards. More importantly, Aircrack-ng tests the reliability of WPA-PSK and WEP keys by cracking them to establish whether they possess the necessary strength. It is an all-rounded cybersecurity tool suitable for enhancing and improving network security.', '', 'https://www.aircrack-ng.org', NULL, 0, '', '0', '', 'teamviewer://hello35'),
	(586, '7', 'KisMAC', 'assets/images/tools/KisMAC.jpg', 'KisMAC', '0', 'KisMAC cybersecurity tool is designed for wireless network security in the MAC OS X operating system. It contains a wide array of features geared towards experienced cybersecurity professionals. Hence, it might not be friendly for newbies compared to other tools used for similar purposes. KisMAC passively scans wireless networks on supported Wi-Fi cards, including Apple��s AirPort Extreme, AirPort, including other third-party cards. KisMAC uses different techniques, such as brute force attacks and exploiting flaws like the wrong generation of security keys and weak scheduling, to crack the security of WPA and WEP keys. Successful cracking means the keys are not secure, and the network is thus vulnerable to attacks.', '', 'https://kismac-ng.org/', NULL, 0, '', '0', '', 'teamviewer://hello36'),
	(587, '8', 'Nmap', 'assets/images/tools/Nmap.jpg', 'Nmap', '0', 'Nmap, commonly known as network mapper, is an open-source and free cybersecurity tool used to scan networks and IT systems to identify existing security vulnerabilities. It is also used to conduct other vital activities such as mapping out potential attack surfaces on a network and monitoring service or host uptime. Nmap provides many benefits as it runs on most of the widely used operating systems and can scan for web vulnerabilities in large or small networks. The Nmap utility provides security professionals with an overview of all network characteristics. The characteristics include the hosts connected to the networks, the types of firewalls or packet filters deployed to secure a network, and the running operating system.', '', 'https://nmap.org', NULL, 0, 'Tools for scanning web vulnerabilities', '0', '', 'teamviewer://hello37'),
	(588, '8', 'Nikto', 'assets/images/tools/Nikto.jpg', 'Nikto', '0', 'Nikto is one of the best cybersecurity tools for conducting web vulnerabilities. It is an open-source tool that cybersecurity experts use to scan web vulnerabilities and manage them. Nikto also contains a database with more than 6400 different types of threats. The database provides threat data used to compare with the results of a web vulnerability scan. The scans usually cover web servers as well as networks. Developers frequently update the database with new threat data such that new vulnerabilities can easily be identified. Also, numerous plugins are developed and released continuously to ensure the tool is compatible with different types of systems.', '', 'https://cirt.net/Nikto2', NULL, 0, '', '0', '', 'teamviewer://hello38'),
	(589, '8', 'Nexpose', 'assets/images/tools/Nexpose.jpg', 'Nexpose', '0', 'Nexpose is a convenient cybersecurity tool that provides security professionals with real-time functionalities for scanning and managing vulnerabilities in on-premise infrastructure. Security teams use it to detect vulnerabilities and identify and minimize potential weak points on a system. Also, Nexus presents security teams with live views of all activities happening in a network. Besides, to ensure the tool contains the most recent threat data, Nexus continually refreshes its database such that it adapts to different types of threat environments in data or software. The tool further allows security professionals to assign a risk score to the identified vulnerabilities such that they are prioritized according to levels of severity. It is a useful feature that helps a coordinated response to multiple vulnerabilities.', '', 'https://www.rapid7.com/products/nexpose/', NULL, 0, '', '0', '', 'teamviewer://hello39'),
	(590, '8', 'Paros Proxy', 'assets/images/tools/Paros Proxy.jpg', 'Paros Proxy', '0', 'Paros Proxy is a security tool based on Java. The tool consists of a collection of handy tools used to conduct security tests to uncover web vulnerabilities. Some of the tools contained in the Paros Proxy utility include vulnerability scanners, a web spider, and a traffic recorder for retaining network activities in real-time. Paros Proxy is useful in identifying intrusion openings in a network. Also, the tool detects common cybersecurity threats such as cross-site scripting and SQL injection attacks. Paros Proxy is advantageous as it is easy to edit using HTTP/HTTPS or rudimentary Java. It is an excellent tool for identifying vulnerability in a network before cyber adversaries can exploit them, causing security breaches.', '', 'https://gitlab.com/kalilinux/packages/paros', NULL, 0, '', '0', '', 'teamviewer://hello40'),
	(591, '8', 'Burp Suite', 'assets/images/tools/Burp Suite.jpg', 'Burp Suite', '0', 'Burp Suite is a robust cybersecurity tool used to enhance the security of a network. Security teams use the tool to conduct real-time scans on systems focused on detecting critical weaknesses. Also, Burp Suite simulates attacks to determine the different methods cybersecurity threats can compromise network security. There are three versions of Burp Suite; Enterprise, Community, and Professional. Enterprise and Professional are commercial versions meaning they are not free. The community version is a free edition, but most of the features are restricted. It only provides the manual tools deemed to be essential. Burp Suite is an appropriate security tool for businesses but can be a bit costly for small businesses.', '', 'https://portswigger.net/burp', NULL, 0, '', '0', '', 'teamviewer://hello41'),
	(592, '9', 'TrueCrypt', 'assets/images/tools/TrueCrypt.jpg', 'TrueCrypt', '0', 'Despite TrueCrypt going for several years without being updated, it is still considered one of the most popular encryption tools. It is designed for on-the-fly encryption. The tool can encrypt an entire storage device, a partition of the storage medium, or create virtual encrypted disks in a file. Also, being a system for encrypting disks, TrueCrypt permits security professionals to encrypt layered content using two different access control types. This is one reason why TrueCrypt remains a popular tool for encryption even after its developers ceased providing it with the necessary updates.', '', 'http://truecrypt.sourceforge.net', NULL, 0, 'Encryption cybersecurity tools', '0', '', 'teamviewer://hello43'),
	(593, '9', 'KeyPass', 'assets/images/tools/KeyPass.jpg', 'KeyPass', '0', 'Cybersecurity experts mostly use KeePass for identity management purposes. It is highly applicable to different types of office settings. It enables system users to use a single password to access all the accounts they use for work reasons. KeyPass has the edge over other types of identity management tools since it combines security with convenience. For example, the tool allows system users to create unique passwords which they can use to secure different accounts. When accessing an account, KeyPass autofill��s the password for that account once the master password has been provided. Since most system or network breaches are caused by erroneous password management, KeePass eliminates this possibility. Security professionals use KeePass to manage security risks caused by human elements.', '', 'https://keepass.info', NULL, 0, '', '0', '', 'teamviewer://hello44'),
	(594, '9', 'Tor', 'assets/images/tools/Tor.jpg', 'Tor', '0', 'Tor is a highly efficient tool used for providing users with privacy when connected to the internet. This is by routing the requests users make to different proxy servers such that it is hard to trace their presence on the internet. Although there exist malicious exit nodes that can be used to sniff internet traffic, carefully using Tor ensures that a user is undetectable. Tor is, however, more applied in ensuring information security compared to preventing cybersecurity incidents.', '', 'https://www.torproject.org', NULL, 0, '', '0', '', 'teamviewer://hello45'),
	(595, '10', 'Pof', 'assets/images/tools/Pof.jpg', 'Pof', '0', 'This is a cybersecurity tool widely used to monitor networks irrespective of the developers having not released updates for a long time. The tool is efficient and streamlined and does not generate additional data traffic during network monitoring. Cybersecurity experts use POf to detect the operating systems of hosts connected to a network. Besides, POf is used to create name lookups, probes, assorted queries, among other functionalities. It is fast and lightweight, making it to be among the widely used network monitoring tools. It is useful for advanced security experts, whereas rookies can experience difficulties learning and using it.', '', 'http://www.baidu.com', NULL, 0, '', '0', '', 'teamviewer://hello47'),
	(596, '10', 'Argus ', 'assets/images/tools/Argus .jpg', 'Argus ', '0', 'Argus is an open-source cybersecurity tool and among the most widely used for analyzing network traffics. Argus is an acronym for Audit Record Generation and Utilization System. It is designed for conducting an in-depth analysis of the data communicated over a network. It has powerful capabilities for sifting through massive amounts of traffic and provides comprehensive and quick reporting.', '', 'http://www.argusone.com/Download.html', NULL, 0, '', '0', ' open-source ', 'teamviewer://hello48'),
	(597, '10', 'OSSEC', 'assets/images/tools/OSSEC.jpg', 'OSSEC', '0', 'OSSEC is an open-source cybersecurity tool for detecting intrusions in a network. It is capable of providing real-time analytics to users regarding the security events of a system. Users can configure it to continually monitor all possible points that might be a source for unauthorized access or entry. These include files, processes, logs, rootkits, and registries. OSSEC is highly beneficial since it can be used on multiple platforms. Examples of such platforms are Windows, Linux, Mac, VMWare ESX, BSD, among others.', '', 'https://www.ossec.net', NULL, 0, '', '0', '', 'teamviewer://hello50'),
	(599, '11', 'Acunetix', 'assets/images/tools/Acunetix.jpg', 'Acunetix', '0', 'More often than not, organizations fear that cybercriminals may directly execute attacks through?social engineering?attacks, internal threats, or through the implemented firewalls. However, the organizations may not consider focusing on security operations on web-based apps such as login pages, online forms, and shopping carts. As such, Acunetix is designed to enable businesses to define defenses for securing against thousands of security threats unique to the sites and applications. Acunetix frequently crawls throughout a system architecture performing convectional attacks to test the effectiveness of the responses of applied security defenses.', '', 'https://www.acunetix.com/', NULL, 0, '', '0', '', 'teamviewer://hello52'),
	(600, '11', 'Forcepoint', 'assets/images/tools/Forcepoint.jpg', 'Forcepoint', '0', 'Network and security admins use Forcepoint to customize SD-Wan such that users are restricted from accessing specific resource contents. The customizations are also used to block attempted exploits or intrusions. Through using Forcepoint, network admins can quickly detect suspicious activities in a network, allowing them to implement appropriate actions. This is advantageous compared to other tools, which first tracks down a problem for the correct measure to be applied. Forcepoint is primarily designed for cloud users, and it includes practical functionalities such as blocking or warning about cloud servers with potential security risks. In other applications, Forcepoint provides extra security and higher levels of access to areas containing critical information or data.', '', 'https://www.forcepoint.com', NULL, 0, '', '0', '', 'teamviewer://hello53'),
	(602, '2', 'BlackLight', 'assets/images/tools/BlackLight.jpg', 'BlackLight', '0', 'BlackBag BlackLight is the number one Mac forensics tool available on the market today, with a price tag of approximately $2,600. BlackLight was launched as a Mac-only forensics tool. Today, it\'s also a great Windows checker. It also analyzes iOS devices as well as Android devices. But it can\'t analyze blueberry devices. The Blacklight itself does not have bit forensics capabilities for bit cloning. They have an additional tool called MacQuisition. MacQuisition runs a stripped-down version of iOS and is priced over $1000 under Apple\'s license. It does a very good job of finding data encryption, while still treating the fused memory connection like a volume label.', 'Mac/Windows', 'https://www.blackbagtech.com/', NULL, 0, 'MAC forensics| Android analytics| data encryption', '0', '', 'teamviewer://hello55'),
	(603, '2', 'AccessData', 'assets/images/tools/AccessData.jpg', 'AccessData', '0', '"AccessData is a leading provider of electronic search, computer and mobile forensics to businesses, law firms, and government agencies. Their digital forensics solutions include the Forensic ToolKit (FTK), a suite that provides comprehensive processing and indexing capabilities so filtering and searching is faster than any other solution on the market.The company is best known for its Mobile forensics tools, including Mobile Phone Examiner Plus (MPE+) and nFIELD. The former enables mobile forensic inspectors to quickly collect, easily identify, and efficiently capture core data that other solutions miss. The latter is an agile solution that enables users to achieve logical and physical data retrieval across all MPE+ enabled mobile devices in just five steps."""', '', 'https://accessdata.com', NULL, 0, 'FTK', '0', '', 'teamviewer://hello56'),
	(604, '2', 'Guidance Software', 'assets/images/tools/Guidance Software.jpg', 'Guidance Software', '0', 'Guidance Software, founded in 1997, developed EnCase forensics Software, a PC-only forensics tool that has remained a mainstay in the forensics industry. The tool made headlines twice, once in 2002 when it was used in the murder trial of David Westerfield to examine his computer for evidence of child pornography, and once when French police used EnCase to find evidence from Richard Colvin Reid, Also known as the shoe Bomber\'s incriminating email.Notable features of EnCase forensics include data acquisition, hard disk recovery (bit-by-bit cloning and making cloned HDDS), complete hard disk level surveys, and fully integrated reporting mechanisms.', 'PC', 'https://www.guidancesoftware.com/', NULL, 0, 'Data acquisition and hard disk recovery', '0', '', 'teamviewer://hello57'),
	(605, '2', 'Magnet Forensics', 'assets/images/tools/Magnet Forensics.jpg', 'Magnet Forensics', '0', 'Developed by former police officers and programmers, Magnet Forensics is a fully digital investigative platform used by more than 3,000 agencies and organizations worldwide. It started out as an Internet carving tool, but has since expanded into a very mature forensics kit. Magnet Forensics takes physical data from mobile phones (most Android phones, iPhone 4 and earlier, and blueberries). This physically retrieved data can then be loaded into tools like Cellebrite.', '', 'https://www.magnetforensics.com/', NULL, 0, 'Mobile phone physical data acquisition', '0', '', 'teamviewer://hello58'),
	(606, '2', 'X-Ways', 'assets/images/tools/X-Ways.jpg', 'X-Ways', '1', '"X-ways is a relative newcomer to digital forensics, but the company has quickly gained acceptance among users because of the speed with which it innovates. X-ways is developed by a Team of German engineers. Its forensics tools have outstanding performance in disk mirroring, disk cloning, virtual RAID reconstruction, remote network drive analysis, remote RAM access, cloud storage access and other aspects. Its disadvantage is that its use requires a wealth of experience."""', '', 'https://www.x-ways.net/', NULL, 0, 'Disk mirroring| disk cloning| virtual RAID reconstruction| remote network drive analysis| remote RAM access| cloud storage access', '0', '', 'teamviewer://hello59'),
	(607, '2', 'Cellebrite Mobile Synchronization', 'assets/images/tools/Cellebrite Mobile Synchronization.jpg', 'Cellebrite Mobile Synchronization', '0', 'Cellebrite Mobile Synchronization is an Israeli company considered a leader in Mobile forensics software. Their famous mobile tool is priced at $12,000 USD, with annual licensing fees around $4,000. The price is high, but the service is top-notch, bringing its insights to mobile devices through Cellebrite\'s unified digital forensics platform.', '', 'https://www.cellebrite.com/', NULL, 0, 'Unified digital forensics platform', '0', '', 'teamviewer://hello60'),
	(608, '2', 'CERT', 'assets/images/tools/CERT.jpg', 'CERT', '0', 'CERT stands for Computer emergency Response team. In the United States, the agency was created in 2003 to protect the nation\'s Internet infrastructure from cyber attacks. They have developed several tools that are widely used in law enforcement, including the CERT Authentication and classification tool. This tool is used to capture RAM and perform field forensics. The product also includes a GNU testing tool plug-in called exploitable, which sorts Linux application vulnerabilities according to their severity. At present, the CERT authentication and classification tool is under open development on GitHub.', '', 'https://www.sei.cmu.edu/publications/software-tools/index.cfm#toolsList', NULL, 0, 'Computer emergency response team', '0', 'Open Source', 'teamviewer://hello61'),
	(609, '2', 'Disk Drill', 'assets/images/tools/Disk Drill.jpg', 'Disk Drill', '0', 'Disk Drill is a widely recognized data recovery tool used in countries around the world to recover files, images, videos, and other data types from a variety of storage devices. CleverFiles, the company behind Disk Drill, is currently working on a new version of the software that will include a range of useful forensics tools. The new version interface exquisite, simple to use, once launched in the forensics market is expected to bring a new and refreshing smooth experience for its users', '', 'https://www.cleverfiles.com/?gclid=Cj0KCQjwv5uKBhD6ARIsAGv9a-xX8wgHPsNRQ1VuSz2NAHLiYXRgPIVlAnc1pUiBMpW4yWGj-qyngaMaAo6QEALw_wcB', NULL, 0, 'Data recovery of pictures| files and videos', '0', '', 'teamviewer://hello62'),
	(610, '3', 'SEED Lab', 'assets/images/tools/SEED Lab.jpg', 'SEED Lab', '0', 'They have developed over 30 labs that cover a wide range of topics in computer and information security, including software security, network security, web security, operating system security and mobile app security. More labs are currently being developed.    Started in 2002, funded by a total of 1.3 million dollars from NSF, and now used by over a thousand educational institutes worldwide, the SEED project\'s objective is to develop hands-on laboratory exercises (called SEED labs) for computer and information security education and help instructors adopt these labs in their curricula.', '', 'https://seedsecuritylabs.org/Labs_16.04/Web/', NULL, 0, 'over 30 labs that cover a wide range of topics', '0', '', 'teamviewer://hello63'),
	(611, '3', 'DVWA', 'assets/images/tools/DVWA.jpg', 'DVWA', '0', 'Damn Vulnerable Web App (DVWA) is a PHP/MySQL web application that is damn vulnerable. Its main goals are to be an aid for security professionals to test their skills and tools in a legal environment, help web developers better understand the processes of securing web applications and aid teachers/students to teach/learn web application security in a class room environment.', '', 'https://dvwa.co.uk', NULL, 0, 'study skills | and test tools in a legal environment', '0', '', 'teamviewer://hello64'),
	(612, '4', 'MyscanTool', 'assets/images/tools/MyscanTool.jpg', 'MyscanTool', '0', 'XXS SCAN', 'Mac/Windows', 'http://localhost:8081/', NULL, 0, 'Xss Scan', '0', 'Open Source', ''),
	(614, '0', 'Qualys', 'assets/images/tools/Qualys.jpg', 'Qualys', '0', 'Whether the site has SSL/TLS misconfiguration and vulnerabilities; For in-depth analysis of https:// URL, including expiration date, overall rating, password, SSL/TLS version, handshake emulation, protocol details, BEAST, etc. Best practice is to test after any SSL/TLS related changes.', 'To work on any website platform', 'https://www.ssllabs.com/ssltest/', NULL, 0, 'Scan SSL server tests online', '1', 'business', 'teamviewer://hello2');
/*!40000 ALTER TABLE `tools` ENABLE KEYS */;

-- 导出  表 myweb.user 结构
CREATE TABLE IF NOT EXISTS `user` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `class_number` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `role` int(11) NOT NULL DEFAULT '2',
  `true_name` varchar(255) DEFAULT NULL,
  `solved_number` int(11) DEFAULT '0',
  PRIMARY KEY (`uid`) USING BTREE,
  UNIQUE KEY `username` (`username`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- 正在导出表  myweb.user 的数据：~1 rows (大约)
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
REPLACE INTO `user` (`uid`, `username`, `password`, `class_number`, `email`, `role`, `true_name`, `solved_number`) VALUES
	(1, 'admin', 'admin', '1', 'admin@123.com', 2, 'admin', 1);
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
