spring:
#数据库的配置Database Configuration

  datasource:
    url: jdbc:mysql://localhost:3306/myweb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    druid:
      #初始化时建立物理连接的个数Number of physical connections established during initialization
      initial-size: 5
      # 最大连接池数量Maximum number of connection pools
      max-active: 30
      # 最小连接池数量Minimum number of connection pools
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒Gets the maximum wait time for a connection, in milliseconds
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒Set the interval for detecting idle connections to be closed, in milliseconds
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间 Minimum time for a connection to remain idle without being expelled
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句 The SQL used to test whether a connection is valid requires a query statement
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      # You are advised to set this parameter to true to ensure performance and security. Apply for connection, if free time is more than timeBetweenEvictionRunsMillis, performing validationQuery test connection is valid
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。When applying for a connection, execute validationQuery to check whether the connection is valid. This configuration degrades performance.
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。When applying for a connection, execute validationQuery to check whether the connection is valid. This configuration degrades performance.
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。Whether to cache preparedStatement, which is PSCache. PSCache provides a huge performance boost for databases that support cursors, such as Oracle. MAXINE's advice is: in mysql, this should be turned off.
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。To enable PSCache, the configuration must be greater than 0, when greater than 0, poolPreparedStatements automatically triggers a change to true.
      max-pool-prepared-statement-per-connection-size: 0
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计. Configure the filters for monitoring statistics interception. After the filters are removed, the SQL on the monitoring interface cannot be counted
      filters: [wall,stat]
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录.Turn on the mergeSql function via the connectProperties property; Slow SQL record
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081

